
import { motion } from "framer-motion";
import { Code2, Rocket, Vote, PercentSquare } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

const timelineSteps = [
  {
    icon: Code2,
    title: "Start Building",
    description: "From Sunday to Friday, Harry and Marcos work heads-down building completely different products from scratch. No constraints. No themes. Just speed and creativity.",
  },
  {
    icon: Rocket,
    title: "Product Drops",
    description: "On Friday night, both products go live on sixty40.dev — complete with screenshots, descriptions, and demo links. You get the full scoop.",
  },
  {
    icon: Vote,
    title: "Cast Your Vote",
    description: "Voting opens Friday night and closes Sunday at 8PM ET. It's anonymous, it's simple, and you only get one vote — so make it count.",
  },
  {
    icon: PercentSquare,
    title: "60/40 Revenue Split",
    description: "Whichever product wins the vote gets 60% of the total revenue generated by both products that week. The runner-up still earns 40%.",
  },
];

export const HowItWorksSection = () => {
  return (
    <section id="how-it-works" className="py-24 px-4 relative overflow-hidden">
      <div className="container mx-auto max-w-7xl">
        <div className="text-center mb-16">
          <Badge className="mb-4 bg-sixty40-purple text-white">
            The Process
          </Badge>
          <h2 className="text-4xl md:text-5xl font-bold mb-6 tracking-tight">
            How Sixty40 Works
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            From concept to revenue split, here's how the weekly competition plays out
          </p>
        </div>

        {/* Timeline Steps */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 relative">
          {/* Animated Progress Line */}
          <div className="absolute top-24 left-0 w-full h-1 hidden lg:block">
            <div className="w-full h-full bg-gray-800/20 rounded-full overflow-hidden">
              <motion.div 
                className="h-full bg-gradient-to-r from-sixty40-orange to-sixty40-blue"
                initial={{ width: "0%" }}
                whileInView={{ width: "100%" }}
                transition={{ duration: 1.5, ease: "easeInOut" }}
                viewport={{ once: true }}
              />
            </div>
          </div>

          {timelineSteps.map((step, index) => (
            <motion.div
              key={step.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.2 }}
              viewport={{ once: true }}
              className={cn(
                "glass-card p-6 relative group transition-all duration-300",
                "hover:bg-white/10 hover:shadow-xl",
                "flex flex-col items-start gap-4"
              )}
            >
              {/* Step Number */}
              <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-sixty40-purple/10 text-sixty40-purple mb-2">
                <step.icon size={24} className="transition-transform duration-300 group-hover:scale-110" />
              </div>
              
              <div>
                <h3 className="text-xl font-bold mb-2 tracking-tight">
                  {step.title}
                </h3>
                <p className="text-muted-foreground leading-relaxed">
                  {step.description}
                </p>
              </div>

              {/* Connector Line (Mobile) */}
              {index < timelineSteps.length - 1 && (
                <div className="absolute -bottom-3 left-1/2 transform -translate-x-1/2 w-1 h-6 bg-gradient-to-b from-sixty40-purple/20 to-transparent lg:hidden" />
              )}
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

