// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqjncrijsuynmwvlstox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxam5jcmlqc3V5bm13dmxzdG94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMjY4MTgsImV4cCI6MjA2MDYwMjgxOH0.KejbtTCmTaE8hf2tAfI7allTbzCqG8x4KNGPCrngH1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);